language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t vdwivedi/docker-react -f  Dockerfile.dev .

script:
  - docker run -e CI=true vdwivedi/docker-react npm run test -- -- coverage